#:import OPACITY_FULL Constants.OPACITY_FULL

<TopPanelLogoButton@TouchRippleButton>:
    size_hint: None, None
    size: '400dp', '104dp'
    pos: '-10dp', '-20dp'
    ripple_color: app.root.COLOR_BACKGROUND
    # on_release: app.root.tpm.add_tab('status')

<Menu3Button@TouchRippleButton>:
    size_hint_y: None
    height: '368dp'
    pos: '0dp', '-40dp'

<ButtonTouchArea@TouchRippleButton>:
    size_hint: None, None
    ripple_color: app.root.COLOR_BACKGROUND
